#target section
- hosts: devlinux
  user: velocity
  become: yes
  connection: ssh
  gather_facts: yes
  
  tasks:
    - name: install java
      action: yum name=java-1.8.0-openjdk-devel.x86_64 state=present
      
    - name: start java
      action: service name=java-1.8.0-openjdk-devel.x86_64 state=started
      
    - name: permission to mnt
      command: chmod -R 777 /mnt  
      
    - name: download tomcat
      action: get_url url=https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.zip dest=/mnt
      
    - name: extract tomcat
      action: unzip src=/mnt/apache-tomcat-9.0.73.zip dest=/mnt
      
    - name: copy gameoflife
      action: copy src=/mnt/game-of-life/gameoflife-web/target/gameoflife.war dest=/mnt/apache-tomcat-9.0.73/webapps/
      
    - name: start tomcat
      action: shell /mnt/apache-tomcat-9.0.73/bin/startup.sh
